# This configuration was used Ebert to review the davidbrusius/task-list repository
# on 10f6e573bee5ccea46b42168c56abb717b32bd41.
# You can make this the default configuration for future reviews by moving this
# file to your repository as `.ebert.yml` and pushing it to GitHub, and tweak
# it as you wish - To know more on how to change this file to better review your
# repository you can go to http://ebert.dev:3000/docs/config and see the configuration
# details.
---
styleguide: plataformatec/linters
engines:
  reek:
    enabled: true
  fixme:
    enabled: true
  eslint:
    enabled: true
  rubocop:
    enabled: true
  brakeman:
    enabled: true
  scss-lint:
    enabled: true
  duplication:
    config:
      languages:
      - ruby
    enabled: false
  remark-lint:
    enabled: true
  bundler-audit:
    enabled: true
exclude_paths:
- bin
- config
- db
- public
- spec
- vendor
